quarkus:
  config:
    profile:
      parent: common
  http:
    port:8080
  log:
    console:
      color: true
      level: DEBUG
      json: false
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:catalog
    flyway:
      default-schema: catalog
      migrate-at-start: true
      locations:
        - db/migration